//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class giohang
    {
        public string tennguoidung { get; set; }
        public int masp { get; set; }
        public string tensp { get; set; }
        public double gia { get; set; }
        public int soluong { get; set; }
        public byte[] anh { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
