//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonxuat
    {
        public int ma { get; set; }
        public Nullable<int> masp { get; set; }
        public int manv { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public string tennguoidung { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
