//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonnhap
    {
        public int ma { get; set; }
        public Nullable<int> masp { get; set; }
        public int manv { get; set; }
        public int mancc { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
    
        public virtual nhacungcap nhacungcap { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
