//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taikhoan()
        {
            this.giohangs = new HashSet<giohang>();
            this.hoadonxuats = new HashSet<hoadonxuat>();
        }
    
        public string tennguoidung { get; set; }
        public string matkhau { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public Nullable<bool> quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonxuat> hoadonxuats { get; set; }
    }
}
